cmake_minimum_required(VERSION 4.3)
project(m1n1)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)
include_directories(build)
include_directories(proxyclient)
include_directories(src)
include_directories(src/dcp)
include_directories(src/dlmalloc)
include_directories(src/libfdt)
include_directories(src/math)
include_directories(src/minilzlib)
include_directories(src/tinf)
include_directories(sysinc)

add_executable(m1n1
        3rdparty_licenses/LICENSE.BSD-2.libfdt
        3rdparty_licenses/LICENSE.BSD-3.arm
        3rdparty_licenses/LICENSE.BSD-3.dwc3
        3rdparty_licenses/LICENSE.CC0
        3rdparty_licenses/LICENSE.GPL-2
        3rdparty_licenses/LICENSE.minlzma
        3rdparty_licenses/LICENSE.OFL-1.1
        3rdparty_licenses/LICENSE.tinf
        build/aarch64-unknown-none-softfloat/release/deps/librust-030900d73449808c.a
        build/aarch64-unknown-none-softfloat/release/deps/libsha1_smol-1c3530bddc181ff2.rlib
        build/aarch64-unknown-none-softfloat/release/deps/libsha1_smol-1c3530bddc181ff2.rmeta
        build/aarch64-unknown-none-softfloat/release/deps/rust-030900d73449808c.d
        build/aarch64-unknown-none-softfloat/release/deps/sha1_smol-1c3530bddc181ff2.d
        build/aarch64-unknown-none-softfloat/release/librust.a
        build/aarch64-unknown-none-softfloat/release/librust.d
        build/aarch64-unknown-none-softfloat/CACHEDIR.TAG
        build/chickens/avalanche.o
        build/chickens/blizzard.o
        build/chickens/cyclone_typhoon.o
        build/chickens/everest.o
        build/chickens/firestorm.o
        build/chickens/hurricane_zephyr.o
        build/chickens/icestorm.o
        build/chickens/monsoon_mistral.o
        build/chickens/sawtooth.o
        build/chickens/twister.o
        build/dcp/dpav_ep.o
        build/dcp/dptx_phy.o
        build/dcp/dptx_port_ep.o
        build/dcp/parser.o
        build/dcp/system_ep.o
        build/dlmalloc/malloc.o
        build/libfdt/fdt.o
        build/libfdt/fdt_addresses.o
        build/libfdt/fdt_empty_tree.o
        build/libfdt/fdt_ro.o
        build/libfdt/fdt_rw.o
        build/libfdt/fdt_strerror.o
        build/libfdt/fdt_sw.o
        build/libfdt/fdt_wip.o
        build/math/exp2f_data.o
        build/math/expf.o
        build/math/powf.o
        build/math/powf_data.o
        build/minilzlib/dictbuf.o
        build/minilzlib/inputbuf.o
        build/minilzlib/lzma2dec.o
        build/minilzlib/lzmadec.o
        build/minilzlib/rangedec.o
        build/minilzlib/xzstream.o
        build/release/deps/libversions-a457d1775ce5cb86.so
        build/release/deps/versions-a457d1775ce5cb86.d
        build/tinf/adler32.o
        build/tinf/crc32.o
        build/tinf/tinfgzip.o
        build/tinf/tinflate.o
        build/tinf/tinfzlib.o
        build/adt.o
        build/afk.o
        build/aic.o
        build/asc.o
        build/bootlogo_128.o
        build/bootlogo_256.o
        build/bootlogo_48.o
        build/build_cfg.h
        build/build_tag.h
        build/chainload.o
        build/chainload_asm.o
        build/chickens.o
        build/clk.o
        build/cpufreq.o
        build/dapf.o
        build/dart.o
        build/dcp.o
        build/dcp_iboot.o
        build/devicetree.o
        build/display.o
        build/dockchannel_uart.o
        build/exception.o
        build/exception_asm.o
        build/fb.o
        build/firmware.o
        build/font.o
        build/font_retina.o
        build/gxf.o
        build/gxf_asm.o
        build/heapblock.o
        build/hv.o
        build/hv_aic.o
        build/hv_asm.o
        build/hv_exc.o
        build/hv_virtio.o
        build/hv_vm.o
        build/hv_vuart.o
        build/hv_wdt.o
        build/i2c.o
        build/iodev.o
        build/iova.o
        build/isp.o
        build/kboot.o
        build/kboot_atc.o
        build/kboot_gpu.o
        build/kboot_t6020_compat.o
        build/librust.a
        build/m1n1-raw.elf
        build/m1n1.bin
        build/m1n1.elf
        build/m1n1.macho
        build/main.o
        build/mcc.o
        build/memory.o
        build/memory_asm.o
        build/mitigations.o
        build/nvme.o
        build/payload.o
        build/pcie.o
        build/pmgr.o
        build/proxy.o
        build/ringbuffer.o
        build/rtkit.o
        build/sart.o
        build/sep.o
        build/sio.o
        build/smc.o
        build/smp.o
        build/spmi.o
        build/start.o
        build/startup.o
        build/string.o
        build/tps6598x.o
        build/tunables.o
        build/tunables_static.o
        build/uart.o
        build/uartproxy.o
        build/usb.o
        build/usb_dwc3.o
        build/utils.o
        build/utils_asm.o
        build/vsprintf.o
        build/wdt.o
        data/bootlogo_128.bin
        data/bootlogo_128.png
        data/bootlogo_256.bin
        data/bootlogo_256.png
        data/bootlogo_48.bin
        data/bootlogo_48.png
        data/makelogo.sh
        font/font.bin
        font/font_retina.bin
        font/makefont.sh
        font/README.md
        font/SourceCodePro-Bold.ttf
        proxyclient/experiments/addrdump.py
        proxyclient/experiments/aes.py
        proxyclient/experiments/agx_1tri.py
        proxyclient/experiments/agx_boot.py
        proxyclient/experiments/agx_cancel.py
        proxyclient/experiments/agx_deps.py
        proxyclient/experiments/agx_dumpstructs.py
        proxyclient/experiments/agx_parallel.py
        proxyclient/experiments/agx_renderframe.py
        proxyclient/experiments/agx_tlb.py
        proxyclient/experiments/agx_tracetimings.py
        proxyclient/experiments/agx_xtest.py
        proxyclient/experiments/aic2_vms.py
        proxyclient/experiments/aic_test.py
        proxyclient/experiments/amcc_err_handler.py
        proxyclient/experiments/ane.py
        proxyclient/experiments/aop_als.py
        proxyclient/experiments/aop_audio.py
        proxyclient/experiments/aop_vt.py
        proxyclient/experiments/audio_capture.py
        proxyclient/experiments/avd.py
        proxyclient/experiments/avd_e.py
        proxyclient/experiments/avd_fw.py
        proxyclient/experiments/chickens.py
        proxyclient/experiments/cpu_id_regs.py
        proxyclient/experiments/cpu_pstate_latencies.py
        proxyclient/experiments/cpu_pstates.py
        proxyclient/experiments/dart_dump.py
        proxyclient/experiments/dcp.py
        proxyclient/experiments/dcp_iboot.py
        proxyclient/experiments/dcpext_iboot.py
        proxyclient/experiments/dmp.py
        proxyclient/experiments/dockchannel_irq.py
        proxyclient/experiments/find_sprr_regs.py
        proxyclient/experiments/fptest.py
        proxyclient/experiments/hacr_trap_bits.py
        proxyclient/experiments/i2c.py
        proxyclient/experiments/isp.py
        proxyclient/experiments/jpeg.py
        proxyclient/experiments/jpeg_doc.md
        proxyclient/experiments/lap.py
        proxyclient/experiments/memdump.py
        proxyclient/experiments/mmio_sweep.py
        proxyclient/experiments/mtp.py
        proxyclient/experiments/ohmmeter.py
        proxyclient/experiments/pcie_enable_devices.py
        proxyclient/experiments/pmp_init.py
        proxyclient/experiments/prores.py
        proxyclient/experiments/scaler.py
        proxyclient/experiments/smc.py
        proxyclient/experiments/smc_watcher.py
        proxyclient/experiments/speaker_amp.py
        proxyclient/experiments/spi.py
        proxyclient/experiments/sprr_test_permissions.py
        proxyclient/experiments/timer_test.py
        proxyclient/experiments/touchbar_apple_prepare.sh
        proxyclient/experiments/touchbar_bad_apple.py
        proxyclient/experiments/touchbar_rainbow.py
        proxyclient/experiments/wfi.py
        proxyclient/hv/README.md
        proxyclient/hv/trace_agx.py
        proxyclient/hv/trace_agx_defer.py
        proxyclient/hv/trace_agx_pwr.py
        proxyclient/hv/trace_all.py
        proxyclient/hv/trace_all_more.py
        proxyclient/hv/trace_aop.py
        proxyclient/hv/trace_atc.py
        proxyclient/hv/trace_avd.py
        proxyclient/hv/trace_cd3217.py
        proxyclient/hv/trace_codecs.py
        proxyclient/hv/trace_dart.py
        proxyclient/hv/trace_dcp.py
        proxyclient/hv/trace_dptx.py
        proxyclient/hv/trace_gpio.py
        proxyclient/hv/trace_i2c.py
        proxyclient/hv/trace_isp.py
        proxyclient/hv/trace_keyboard.py
        proxyclient/hv/trace_mesa.py
        proxyclient/hv/trace_mtp.py
        proxyclient/hv/trace_nvme.py
        proxyclient/hv/trace_pmgr.py
        proxyclient/hv/trace_pmp.py
        proxyclient/hv/trace_prores.py
        proxyclient/hv/trace_smc.py
        proxyclient/hv/trace_spmi.py
        proxyclient/hv/trace_wlan.py
        proxyclient/hv/trace_z2.py
        proxyclient/m1n1/agx/__init__.py
        proxyclient/m1n1/agx/channels.py
        proxyclient/m1n1/agx/context.py
        proxyclient/m1n1/agx/event.py
        proxyclient/m1n1/agx/initdata.py
        proxyclient/m1n1/agx/object.py
        proxyclient/m1n1/agx/render.py
        proxyclient/m1n1/agx/shim.py
        proxyclient/m1n1/agx/uapi.py
        proxyclient/m1n1/fw/afk/__init__.py
        proxyclient/m1n1/fw/afk/epic.py
        proxyclient/m1n1/fw/afk/rbep.py
        proxyclient/m1n1/fw/agx/__init__.py
        proxyclient/m1n1/fw/agx/channels.py
        proxyclient/m1n1/fw/agx/cmdqueue.py
        proxyclient/m1n1/fw/agx/handoff.py
        proxyclient/m1n1/fw/agx/initdata.py
        proxyclient/m1n1/fw/agx/microsequence.py
        proxyclient/m1n1/fw/aop/__init__.py
        proxyclient/m1n1/fw/aop/aopep.py
        proxyclient/m1n1/fw/aop/base.py
        proxyclient/m1n1/fw/aop/client.py
        proxyclient/m1n1/fw/aop/ipc.py
        proxyclient/m1n1/fw/asc/__init__.py
        proxyclient/m1n1/fw/asc/base.py
        proxyclient/m1n1/fw/asc/crash.py
        proxyclient/m1n1/fw/asc/ioreporting.py
        proxyclient/m1n1/fw/asc/kdebug.py
        proxyclient/m1n1/fw/asc/mgmt.py
        proxyclient/m1n1/fw/asc/oslog.py
        proxyclient/m1n1/fw/asc/syslog.py
        proxyclient/m1n1/fw/avd/__init__.py
        proxyclient/m1n1/fw/avd/decoder.py
        proxyclient/m1n1/fw/dcp/__init__.py
        proxyclient/m1n1/fw/dcp/client.py
        proxyclient/m1n1/fw/dcp/dcpav.py
        proxyclient/m1n1/fw/dcp/dcpep.py
        proxyclient/m1n1/fw/dcp/iboot.py
        proxyclient/m1n1/fw/dcp/ipc.py
        proxyclient/m1n1/fw/dcp/manager.py
        proxyclient/m1n1/fw/dcp/parse_log.py
        proxyclient/m1n1/fw/isp/__init__.py
        proxyclient/m1n1/fw/isp/isp_base.py
        proxyclient/m1n1/fw/isp/isp_chan.py
        proxyclient/m1n1/fw/isp/isp_cmd.py
        proxyclient/m1n1/fw/isp/isp_opcodes.py
        proxyclient/m1n1/fw/isp/isp_vid.py
        proxyclient/m1n1/fw/__init__.py
        proxyclient/m1n1/fw/ane.py
        proxyclient/m1n1/fw/common.py
        proxyclient/m1n1/fw/mtp.py
        proxyclient/m1n1/fw/pmp.py
        proxyclient/m1n1/fw/smc.py
        proxyclient/m1n1/hv/gdbserver/features/aarch64-core.xml
        proxyclient/m1n1/hv/gdbserver/features/aarch64-fpu.xml
        proxyclient/m1n1/hv/gdbserver/features/target.xml
        proxyclient/m1n1/hv/gdbserver/__init__.py
        proxyclient/m1n1/hv/__init__.py
        proxyclient/m1n1/hv/types.py
        proxyclient/m1n1/hv/virtio.py
        proxyclient/m1n1/hv/virtutils.py
        proxyclient/m1n1/hw/codecs/__init__.py
        proxyclient/m1n1/hw/codecs/cs42l84.py
        proxyclient/m1n1/hw/codecs/ssm3515.py
        proxyclient/m1n1/hw/admac.py
        proxyclient/m1n1/hw/aes.py
        proxyclient/m1n1/hw/agx.py
        proxyclient/m1n1/hw/ane.py
        proxyclient/m1n1/hw/asc.py
        proxyclient/m1n1/hw/atc.py
        proxyclient/m1n1/hw/dart.py
        proxyclient/m1n1/hw/dart8020.py
        proxyclient/m1n1/hw/dart8110.py
        proxyclient/m1n1/hw/dockchannel.py
        proxyclient/m1n1/hw/dwc3.py
        proxyclient/m1n1/hw/i2c.py
        proxyclient/m1n1/hw/isp.py
        proxyclient/m1n1/hw/jpeg.py
        proxyclient/m1n1/hw/mca.py
        proxyclient/m1n1/hw/nco.py
        proxyclient/m1n1/hw/pmgr.py
        proxyclient/m1n1/hw/pmu.py
        proxyclient/m1n1/hw/prores.py
        proxyclient/m1n1/hw/scaler.py
        proxyclient/m1n1/hw/sep.py
        proxyclient/m1n1/hw/spi.py
        proxyclient/m1n1/hw/spmi.py
        proxyclient/m1n1/hw/spmi1.py
        proxyclient/m1n1/hw/spmi4.py
        proxyclient/m1n1/hw/uat.py
        proxyclient/m1n1/trace/__init__.py
        proxyclient/m1n1/trace/agx.py
        proxyclient/m1n1/trace/asc.py
        proxyclient/m1n1/trace/dart.py
        proxyclient/m1n1/trace/dockchannel.py
        proxyclient/m1n1/trace/gpio.py
        proxyclient/m1n1/trace/i2c.py
        proxyclient/m1n1/trace/isp.py
        proxyclient/m1n1/trace/pcie.py
        proxyclient/m1n1/trace/spi.py
        proxyclient/m1n1/trace/spmi.py
        proxyclient/m1n1/__init__.py
        proxyclient/m1n1/adt.py
        proxyclient/m1n1/apple_regs.json
        proxyclient/m1n1/arm_regs.json
        proxyclient/m1n1/asm.py
        proxyclient/m1n1/constructutils.py
        proxyclient/m1n1/find_regs.py
        proxyclient/m1n1/gpiola.py
        proxyclient/m1n1/hostutils.py
        proxyclient/m1n1/ishell.py
        proxyclient/m1n1/ishell_ext.py
        proxyclient/m1n1/loadobjs.py
        proxyclient/m1n1/macho.py
        proxyclient/m1n1/malloc.py
        proxyclient/m1n1/proxy.py
        proxyclient/m1n1/proxyutils.py
        proxyclient/m1n1/setup.py
        proxyclient/m1n1/shell.py
        proxyclient/m1n1/sysreg.py
        proxyclient/m1n1/tgtypes.py
        proxyclient/m1n1/toolchain.py
        proxyclient/m1n1/utils.py
        proxyclient/m1n1/xnutools.py
        proxyclient/tools/admac_stream.py
        proxyclient/tools/chainload.py
        proxyclient/tools/codecshell.py
        proxyclient/tools/dump_pmgr.py
        proxyclient/tools/freebsd.py
        proxyclient/tools/ishell.py
        proxyclient/tools/linux.py
        proxyclient/tools/picocom-sec.sh
        proxyclient/tools/pmgr_adt2dt.py
        proxyclient/tools/pmp_assist.py
        proxyclient/tools/reboot.py
        proxyclient/tools/reset_panic_counter.py
        proxyclient/tools/run_guest.py
        proxyclient/tools/run_guest_kernel.sh
        proxyclient/tools/second_proxy.py
        proxyclient/tools/shell.py
        proxyclient/tools/smccli.py
        rust/src/gpu/hw/mod.rs
        rust/src/gpu/hw/t600x.rs
        rust/src/gpu/hw/t602x.rs
        rust/src/gpu/hw/t8103.rs
        rust/src/gpu/hw/t8112.rs
        rust/src/gpu/initdata.rs
        rust/src/gpu/mod.rs
        rust/src/gpu/raw.rs
        rust/src/gpu/types.rs
        rust/src/adt.rs
        rust/src/apfs.rs
        rust/src/chainload.rs
        rust/src/dlmalloc.rs
        rust/src/float.rs
        rust/src/gpt.rs
        rust/src/lib.rs
        rust/src/nvme.rs
        rust/src/print.rs
        rust/src/usb4.rs
        rust/versions/src/lib.rs
        rust/versions/Cargo.lock
        rust/versions/Cargo.toml
        rust/Cargo.lock
        rust/Cargo.toml
        src/chickens/avalanche.c
        src/chickens/blizzard.c
        src/chickens/cyclone_typhoon.c
        src/chickens/everest.c
        src/chickens/firestorm.c
        src/chickens/hurricane_zephyr.c
        src/chickens/icestorm.c
        src/chickens/monsoon_mistral.c
        src/chickens/sawtooth.c
        src/chickens/twister.c
        src/dcp/dpav_ep.c
        src/dcp/dpav_ep.h
        src/dcp/dptx_phy.c
        src/dcp/dptx_phy.h
        src/dcp/dptx_port_ep.c
        src/dcp/dptx_port_ep.h
        src/dcp/parser.c
        src/dcp/parser.h
        src/dcp/system_ep.c
        src/dcp/system_ep.h
        src/dlmalloc/malloc.c
        src/dlmalloc/malloc_config.h
        src/libfdt/fdt.c
        src/libfdt/fdt.h
        src/libfdt/fdt_addresses.c
        src/libfdt/fdt_empty_tree.c
        src/libfdt/fdt_overlay.c
        src/libfdt/fdt_ro.c
        src/libfdt/fdt_rw.c
        src/libfdt/fdt_strerror.c
        src/libfdt/fdt_sw.c
        src/libfdt/fdt_wip.c
        src/libfdt/libfdt.h
        src/libfdt/libfdt_env.h
        src/libfdt/libfdt_internal.h
        src/math/exp2f_data.c
        src/math/exp2f_data.h
        src/math/expf.c
        src/math/libm.h
        src/math/powf.c
        src/math/powf_data.c
        src/math/powf_data.h
        src/minilzlib/dictbuf.c
        src/minilzlib/inputbuf.c
        src/minilzlib/lzma2dec.c
        src/minilzlib/lzma2dec.h
        src/minilzlib/lzmadec.c
        src/minilzlib/lzmadec.h
        src/minilzlib/minlzlib.h
        src/minilzlib/minlzma.h
        src/minilzlib/rangedec.c
        src/minilzlib/xzstream.c
        src/minilzlib/xzstream.h
        src/tinf/adler32.c
        src/tinf/crc32.c
        src/tinf/tinf.h
        src/tinf/tinfgzip.c
        src/tinf/tinflate.c
        src/tinf/tinfzlib.c
        src/adt.c
        src/adt.h
        src/afk.c
        src/afk.h
        src/aic.c
        src/aic.h
        src/aic_regs.h
        src/arm_cpu_regs.h
        src/asc.c
        src/asc.h
        src/chainload.c
        src/chainload.h
        src/chainload_asm.S
        src/chickens.c
        src/chickens.h
        src/clk.c
        src/clk.h
        src/cpu_regs.h
        src/cpufreq.c
        src/cpufreq.h
        src/dapf.c
        src/dapf.h
        src/dart.c
        src/dart.h
        src/dcp.c
        src/dcp.h
        src/dcp_iboot.c
        src/dcp_iboot.h
        src/devicetree.c
        src/devicetree.h
        src/display.c
        src/display.h
        src/dockchannel_uart.c
        src/dockchannel_uart.h
        src/exception.c
        src/exception.h
        src/exception_asm.S
        src/fb.c
        src/fb.h
        src/firmware.c
        src/firmware.h
        src/gxf.c
        src/gxf.h
        src/gxf_asm.S
        src/heapblock.c
        src/heapblock.h
        src/hv.c
        src/hv.h
        src/hv_aic.c
        src/hv_asm.S
        src/hv_exc.c
        src/hv_virtio.c
        src/hv_vm.c
        src/hv_vuart.c
        src/hv_wdt.c
        src/i2c.c
        src/i2c.h
        src/iodev.c
        src/iodev.h
        src/iova.c
        src/iova.h
        src/isp.c
        src/isp.h
        src/kboot.c
        src/kboot.h
        src/kboot_atc.c
        src/kboot_atc.h
        src/kboot_gpu.c
        src/kboot_t6020_compat.c
        src/keyboard_types.h
        src/main.c
        src/mcc.c
        src/mcc.h
        src/memory.c
        src/memory.h
        src/memory_asm.S
        src/midr.h
        src/mitigations.c
        src/mitigations.h
        src/nvme.c
        src/nvme.h
        src/payload.c
        src/payload.h
        src/pcie.c
        src/pcie.h
        src/pmgr.c
        src/pmgr.h
        src/proxy.c
        src/proxy.h
        src/ringbuffer.c
        src/ringbuffer.h
        src/rtkit.c
        src/rtkit.h
        src/sart.c
        src/sart.h
        src/sep.c
        src/sep.h
        src/sio.c
        src/sio.h
        src/smc.c
        src/smc.h
        src/smp.c
        src/smp.h
        src/soc.h
        src/spmi.c
        src/spmi.h
        src/start.S
        src/startup.c
        src/string.c
        src/tps6598x.c
        src/tps6598x.h
        src/tunables.c
        src/tunables.h
        src/tunables_static.c
        src/types.h
        src/uart.c
        src/uart.h
        src/uart_regs.h
        src/uartproxy.c
        src/uartproxy.h
        src/usb.c
        src/usb.h
        src/usb_dwc3.c
        src/usb_dwc3.h
        src/usb_dwc3_regs.h
        src/usb_types.h
        src/utils.c
        src/utils.h
        src/utils_asm.S
        src/vsprintf.c
        src/vsprintf.h
        src/wdt.c
        src/wdt.h
        src/xnuboot.h
        sysinc/assert.h
        sysinc/endian.h
        sysinc/errno.h
        sysinc/limits.h
        sysinc/malloc.h
        sysinc/math.h
        sysinc/string.h
        tests/python/test_proxyclient/test_m1n1/conftest.py
        tests/python/test_proxyclient/test_m1n1/test_asm.py
        tests/python/test_proxyclient/test_m1n1/test_loadobjs.py
        tests/python/test_proxyclient/test_m1n1/test_toolchain.py
        tools/gen_reg_class.py
        tools/gen_reg_include.py
        tools/kmutil.py
        tools/README.md
        tools/reg2json.py
        tools/reg_filter.py
        udev/80-m1n1.rules
        AGENTS.md
        CODEOWNERS
        config.h
        docker-compose.yml
        Dockerfile
        LICENSE
        m1n1-raw.ld
        m1n1.conf.example
        m1n1.ld
        m5_adt.bin
        m5_adt.txt
        m5_adt_parsed.txt
        m5_t8142.dts
        Makefile
        pytest.ini
        README.md
        requirements.ini
        requirements.txt
        restore_1789239796.log
        restore_1789239900.log
        version.sh)
